import './globals.css'
import {whitney, inter} from './fonts';
import Header from '../components/header';
import Footer from '../components/footer';



export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <header className={`bg-white ${whitney.className}`}>
      <Header />
      </header>
      {children}
      </body>
      <footer className={whitney.className}>
      <Footer  />
      </footer>
    </html>
  )
}
