import './globals.css'
import {whitney, inter} from './fonts';
import Header from '../components/Header';
import Footer from '../components/Footer';


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body className='bg-[#2424240D] bg-none text-black'>
      <header className={`${whitney.className}`}>
      <Header />
      </header>
      {children}
      <footer className={`${whitney.className}`}>
      <Footer  />
      </footer>
      </body>
    </html>
  )
}
